modLoader = "javafml"
loaderVersion = "*"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Meza"
description = '''
Turn off the Christmas chests for good.
'''
logoFile = "assets/${id}/nochest.png"
logoBlur = false

