modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "disablechristmaschests"
version = "${version}"
displayName = "Disable Christmas Chests"
authors = "Meza"
description = '''
Turn off the Christmas chests for good.
'''
logoFile = "assets/disablechristmaschests/nochest.png"

[[dependencies.disablechristmaschests]]
modId = "neoforge"
mandatory = true
versionRange = "[20.4.29-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.disablechristmaschests]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "disablechristmaschests-client.mixins.json"
